import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container0: {flexDirection: 'column', justifyContent: 'center'},
  container1: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  imgContain: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  Row1: {flexDirection: 'row', alignItems: 'center'},
  textInput: {
    width: '100%',
    height: 45,
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginBottom: 0,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: 'white',
    elevation: 0,
    fontSize: 16,
    color: '#000',
    borderColor: '#dfdfdf',
  },
  inputGroup2: {marginBottom: 6, marginTop: 0, width: '100%'},
  btnSubmit: {
    borderRadius: 4,
    borderColor: '#000',
    backgroundColor: '#E51A47',
    marginBottom: 0,
    height: 45,
    width: '100%',
    textAlign: 'center',
    alignItems: 'center',
  },
  btnSubmit_st1: {backgroundColor: '#fff'},
  btnSubmitTxt: {color: '#fff', fontSize: 14, fontWeight: 'bold'},
  btnSubmit_st1Txt: {color: '#333'},
  login_btnGroup2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  login_btnGroup: {paddingVertical: 12, paddingHorizontal: 13},
  social_btn: {
    borderRadius: 4,
    borderColor: '#000',
    marginBottom: 10,
    height: 45,
    width: '100%',
    textAlign: 'center',
    paddingLeft: 20,
  },
  social_txt: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    paddingRight: '10%',
  },
  social_group: {marginBottom: 6, width: '100%', flex: 1},
  social_img: {width: 18, height: 18},
  subtitle: {fontSize: 16, fontWeight: '500'},
  text2: {fontSize: 16},
  findButton: {
    width: '100%',
    height: 55,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  button1: {
    width: 127,
    height: 45,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#E51A47',
    borderWidth: 1,
    marginLeft: 8,
  },
  button2: {
    width: 101,
    height: 45,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#E51A47',
    borderWidth: 1,
    marginLeft: 8,
  },
  button3: {
    width: '100%',
    height: 45,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#E51A47',
    borderWidth: 1,
    marginBottom: 10,
  },
  passInfo: {color: '#E51A47', marginBottom: 10, marginTop: 5},
  underLine: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginVertical: 20,
  },
});
