import {StyleSheet, Dimensions, Platform} from 'react-native';
import {Fonts} from './Fonts';
export default StyleSheet.create({
  bluebackgroundbutton: {
    height: 45,
    backgroundColor: '#28B766',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  bluebackgroundbuttonrow: {
    height: 45,
    backgroundColor: '#28B766',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    flexDirection: 'row',
  },
  bluebutton50: {
    height: 45,
    backgroundColor: '#28B766',
    justifyContent: 'center',
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  blueborderbutton: {
    height: 45,
    width: 127,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#28B766',
    justifyContent: 'center',
    alignItems: 'center',
  },
  boldwhite16: {color: 'white', fontSize: 16, fontWeight: 'bold'},
  mediumwhitetxt16: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  textinput: {
    height: 45,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E3E3E3',
    paddingHorizontal: 15,
    fontSize: 16,
  },
  container: {flex: 1, backgroundColor: 'white'},
  container01: {flex: 1, backgroundColor: 'white', padding: 15},
  mediumtxt16: {fontWeight: '600', fontSize: 16},
  bluetext16: {
    color: '#28B766',
    fontSize: 16,
    fontWeight: '600',
  },
  underline: {
    backgroundColor: '#E5E5E5',
    height: 1,
    marginVertical: 15,
  },
  underline1: {
    backgroundColor: '#E5E5E5',
    height: 1,
  },
  underline100: {
    backgroundColor: '#E5E5E5',
    height: 1,
    flex: 1,
  },
  workonoffview: {
    height: 65,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: '#E5E5E5',
    borderBottomWidth: 1,
  },
  workbutton: {width: 65, height: 35},
  toptabOn: {
    flex: 1,
    height: 45,
    borderBottomWidth: 2,
    borderBottomColor: '#28B766',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toptabOff: {
    flex: 1,
    height: 45,
    borderBottomWidth: 2,
    borderBottomColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toptabontext: {
    color: '#28B766',
    fontSize: 17,
    fontWeight: 'bold',
  },
  toptabofftext: {
    color: '#AAAAAA',
    fontSize: 17,
    fontWeight: '600',
  },
  toptabview: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  noticeview: {
    height: 45,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6F6F6',
    paddingHorizontal: 15,
  },
  mainbottomtabOn: {
    backgroundColor: '#28B766',
    flex: 1,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainbottomtabView: {
    height: 50,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderTopColor: '#E5E5E5',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  mainbottomtxtOn: {
    color: 'white',
    fontWeight: '600',
  },
  mainbottomtxtOff: {
    color: 'black',
  },
  mainbottomtabOff: {
    flex: 1,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  greytxt16: {fontSize: 16, color: '#777777'},
  boldgreytxt16: {
    fontSize: 16,
    color: '#777777',
    fontWeight: 'bold',
  },
  mediumgreytxt16: {
    fontSize: 16,
    color: '#777777',
    fontWeight: '600',
  },
  accodiontitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    padding: 15,
    backgroundColor: '#F9F9F9',
  },
  mediumtxt18: {fontSize: 18, fontWeight: '600'},
  Row: {flexDirection: 'row', alignItems: 'center', flex: 1},
  Row1: {flexDirection: 'row', alignItems: 'center'},
  boldtxt18: {color: 'black', fontWeight: 'bold', fontSize: 18},
  topdelstateview: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 45,
    borderRadius: 5,
    marginBottom: 15,
  },
  footerbtnview: {
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
